n1 = int(input('Um valor: '))
n2 = int(input('Outro valor: '))
print('A soma é {}'.format(n1+n2))
print('A subtração é {}'.format(n1-n2))
print('A multiplicação é {}'.format(n1*n2))
print('A divisão é {}'.format(n1/n2))
print('A potencia é {}'.format(n1**n2))